### ISSUE TITLE
Add option to send content to latex editor

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#10]
It would be great if we could send the content/latex-source from a question statement/hint/solution to the latex editor. Eventually this will be how we want to modify the content.

Bonus points: Save the edits into a separate file/database entry.

**Comment by wayneyu** [comment]
Add /edit to the end of a question's url to access the edit options

Right now the changes are submitted (see "submit changes" button in question view) modifies the question in the database.

We can create a separate collection to host the submitted questions.

**Comment by BernhardKonrad** [comment]
How about a extra keys `foo_suggested`, which can then be approved to overwrite `foo` in a second step? (`foo` being `hints`, `solutions`, `final_answer`, `tags`)
