### ISSUE TITLE
Add zoom-bubble-chart to topics using d3

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#106]
This work is done on branch [zoom-bubble-chart](/wayneyu/merapp/tree/zoom-bubble-chart).

**Comment by BernhardKonrad** [comment]
Great work today! Let's put the todo list here, as discussed:
- [x] Deactivate link when not in zoom mode, or display topic label (for @sidazhou)
- [x] Place svg appropriately on page, above the full list of topics and in its own div (for @sidazhou)
- [x] Clean up source code, eg all javascript should be in separate file (for @sidazhou)
- [x] Add url field to json object (for @BernhardKonrad)
- [x] Create json dynamically and obtain per GET request (for @BernhardKonrad)
- [x] Replace `Await.result` with asynchronous equivalend (for @wayneyu)

**Comment by BernhardKonrad** [comment]
The JSON data is now obtained directly from mongodb. So all that's left to do is prettification, @sidazhou.

@wayneyu: Do you know how we could remove the `Await.result` that I'm using in the TopicController? https://github.com/wayneyu/merapp/blob/zoom-bubble-chart/app/controllers/TopicController.scala#L100-L101

**Comment by wayneyu** [comment]
Use UserAwaredAction.async instead of Action. An example is TopicController.topic(topic: String)

**Comment by BernhardKonrad** [comment]
Hm, I tried that and it still complains about the types. There is a second, nested, `Await.result` that may have something to do with it!? https://github.com/wayneyu/merapp/blob/zoom-bubble-chart/app/controllers/TopicController.scala#L131-L132

**Comment by BernhardKonrad** [comment]
Ok, the `Await.result` is removed. I could not quite get a for-comprehension to work, we may want to come back to that later, but it's ok for now: https://github.com/wayneyu/merapp/blob/zoom-bubble-chart/app/controllers/TopicController.scala#L101-L120
