### ISSUE TITLE
Search for keywords in any order

### ISSUE THREAD

**Issue by wayneyu** [wayneyu/merapp#12]
Currently, search uses the regex `.*word1.*word2.*word3.*` . Make regex match keywords in any order.

**Comment by BernhardKonrad** [comment]
Would this do it? `^(?=.*word1)(?=.*word2)(?=.*word3).*$`
May have problems with newline characters (which we could remove from the search string)
(from http://stackoverflow.com/questions/3533408/regex-i-want-this-and-that-and-that-in-any-order)

**Comment by wayneyu** [comment]
Issue is solved in e45c93d28a2084917f46694e40009728b0da8353 using mongodb's built-in text search feature.
In addition, the search uses mongo's "textScore" metadata to sort results by relevance.
