### ISSUE TITLE
List all contributors on team page

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#21]
This info is in the field `contributors` and `solvers`.

**Comment by BernhardKonrad** [comment]
@wayneyu Could you please help me / point me to a resource on how to rewrite
`db.questions.runCommand({count: 'questions', query: { flags: "QGS"}})`
and
`db.questions.distinct("contributors")`
in reactive mongo?

**Comment by wayneyu** [comment]
create a method in MongoDAO.scala:

def distinctContributors(): Future[Stream[BSONDocument]] = {

val command = Aggregate(questionCollection.name, Seq(
Unwind("contributors"),
GroupField("contributors")("contributors" -> First("contributors")),
Project("_id"->BSONInteger(0), "contributors"->BSONInteger(1))
))
db.command(command)
}

then call in QuestionController:

 def contributors = UserAwaredAction.async { implicit context => MongoDAO.
distinctContributors().map { st => Ok(BSONArrayFormat.writes(BSONArray(
st.map(d => d.getAs[BSONString]("contributors").getOrElse(BSONArray(Nil)))
))) } }

And for the count:

val count = db.command(Count(
questionCollection.name,
Some(BSONDocument("flags" -> "QGS"))
))

**Comment by BernhardKonrad** [comment]
That's great, thanks a lot!
