### ISSUE TITLE
Add images to public folder and update links in database accordingly

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#23]
Currently we have 243 image files that total to 48mb. The size is relatively small, so we could store them in the `public` folder. If we do so, is it possible to store new images via a post request?

**Comment by wayneyu** [comment]
Since json_data folder is already in public, you can access any files/images like this: /assets/raw_database/json_data/...

So to display the images, all you have to do is to put them in a folder under json_data and call them with:
`<img src="/assets/raw_database/json_data/..." />`

**Comment by BernhardKonrad** [comment]
Cool, thanks! I will do that and update the links in the `json_data` and database.

**Comment by BernhardKonrad** [comment]
The follow-up task will be: Can we add an upload tool, so that people other than @wayneyu and myself can easily add images?

**Comment by BernhardKonrad** [comment]
Good work on the upload feature! Fantastic.
