### ISSUE TITLE
Add an authentication system

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#24]
Maybe this is a good start: http://securesocial.ws/
This may also be helpful: https://www.tunnelbear.com/development/authenticating-users-in-the-play-framework/

**Comment by wayneyu** [comment]
I got authentication to work locally with an in-memory user table. Will try to implement a database for user lookup this week. Hopefully I can make it production ready by the end of the week.

**Comment by BernhardKonrad** [comment]
You're amazing. Can't wait!

**Comment by wayneyu** [comment]
Implemented the user database with Redis. Need to verify before releasing the feature to production.

**Comment by BernhardKonrad** [comment]
Any way you can push this to a feature branch? Is there anything we could help you with?

**Comment by wayneyu** [comment]
I still have to implement some backup mechanism for the user database. 
You can maybe try to improve the user access workflow, eg. improve login/logout access from main view.

All you need to install to run the authentication system is redis-server (redis-client is installed through sbt)
`sudo apt-get install redis-server`

Currently, only google+ and user/password login methods are implemented.

**Comment by BernhardKonrad** [comment]
Do you want to choose a fitting style, @WillThompson? There are plenty of templates online, eg
http://designscrazed.org/css-html-login-form-templates/
http://www.freshdesignweb.com/css-login-form-templates.html

**Comment by WillThompson** [comment]
@BernhardKonrad: Sure thing. I'll get around to it tonight.

**Comment by BernhardKonrad** [comment]
Awesome. We could also use bootstrap for that: http://bootsnipp.com/tags/login
Maybe something fancy like http://bootsnipp.com/snippets/featured/full-page-sign-in
