### ISSUE TITLE
Figure out workflow to update deployed version

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#3]
Does heroku always deploy `master`? If so, we should re-think how we work with the branches to make sure my script can automatically update the deployed version.

**Comment by wayneyu** [comment]
you can choose which branch to push to heroku with:
git push heroku yourbranch:master

**Comment by BernhardKonrad** [comment]
Oh, thanks! I will push develop then. Which makes me wonder if we really need different branches at this point. The app is not really live anyway.
