### ISSUE TITLE
Add option to rate easiness

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#66]
After we have a login in place, see #24, give logged-in users the option to vote on the easiness of a question.

@WillThompson, do you think a 5-star (0, 0.5, 1, 1.5, ..., 5) system is ideal? Maybe we can have something more fitting than stars (hotness? thumbs-up/down? michael-ward-score?).
@wayneyu, we need to store which questions each user voted on. Should the question also know how many votes it got?
If it helps, I can give you the individual votes per question (instead of the aggregate that we currently use).

**Comment by WillThompson** [comment]
I certainly think a 5-star (or 5-MWard haha) rating makes more sense than the percentage bar. I also don't think we should go to anymore than 5 or 6 ratings. Maybe we can use the "5-check mark" system?

Can we make it so the more stars a question is rated, the harder it is.

**Comment by BernhardKonrad** [comment]
I like the 5 check marks. And absolutely, we can choose if lots means easy or hard. I'm sure you can find templates online, or we write our own.

**Comment by BernhardKonrad** [comment]
That's great. How did you convert the previous votes? We have a database of all individual questions (on scale 0-100) if that helps, @wayneyu

**Comment by wayneyu** [comment]
I don't use previous votes. The new rating is updated base on old rating \* num_votes.
And although each user can vote many times, only the last vote is used to update the question's rating.

**Comment by BernhardKonrad** [comment]
Nice, that's good enough for the average. We could periodically clean the list of votes, deleting older votes from the same user. But more importantly:
1. Should we scale the 1-7 rating to 0-100, or go with 1-7?
2. We should show a user his most recent rating on a question they already rated.

**Comment by wayneyu** [comment]
Why do you want the timestamp if you are deleting older votes from the same user anyways?
1. I assume 1-100 has increment of 1? I doubt there's a need for that finer grain of control for the rating, unless you want to interpret the difference between like 78% and 79%.
   If possible i'd like a half-check mark better, it's visually nicer and spacially easier to manage.
2. That's already done.

**Comment by BernhardKonrad** [comment]
I guess deleting (even outdated) data is not necessary. I would want the timestamp so that I know when people study, and what different cohorts/years think.
1. It's just that the old rating was 0-100. I'm fine with any number of full or half checkmarks. In fact, I was hoping that you and @WillThompson would have some input on that. Do you like the idea of giving a text interpretation with it (Impossible - Difficult - ... - Easy - Aced it)?
2. Good work. It would be nice to have a develop version somewhere so that it's easier to test it. Currently downloading the latest version and starting all the servers, is a little inconvenient...
