### ISSUE TITLE
Reduce number of checkmarks?

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#88]
Hey @WillThompson, @wayneyu, now that we have the code for a checkmark system (for question difficulty) in place, let's decide on how many options we want to give to people.

We currently have 10:
- 1 = impossible
- 2 = very difficult
- 3 = difficult
- 4 = a little difficult
- 5 = a good challenge
- 6 = ok
- 7 = relatively simple
- 8 = simple
- 9 = very simple
- 10 = aced it

I think that's too many. Many websites go with 5 options, which may be just enough for us:
- 1 = very difficult
- 2 = difficult
- 3 = a good challenge
- 4 = simple
- 5 = aced it

Do we need more? Less? Use different names?

Please note that we can be more fine-grained when we display the average to users ([1,1.5,...4.5,5], or even [1, 1.1, ..., 4.9, 5.0]).

**Comment by WillThompson** [comment]
@BernhardKonrad @wayneyu - I think that 5 check marks is plenty. I think that anymore than that doesn't give that much more information.

BTW: I think including the text next to the number of checks is a good idea. It gives students a good understanding of what we think the number of check marks means in an intuitive sense. (i.e. 3/5 means "a good challenge")

**Comment by wayneyu** [comment]
@WillThompson @BernhardKonrad . I agree 5 check marks is enough. It looks cleaner too.

**Comment by BernhardKonrad** [comment]
Thanks!
